wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.2
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      4: 3.8.2
      5: 0.10.31
      8:
      - 1
      - 5
architecture:
  desc: null
  value: CNN
batch_size:
  desc: null
  value: 256
cutout_size:
  desc: null
  value: 54
dataset:
  desc: null
  value: test
epochs:
  desc: null
  value: 2
